language: erlang

matrix:
  include:
    - sudo: required
      dist: trusty
      group: edge
      env:
      - DIST=trusty
    - sudo: required
      env:
      - DIST=precise

env:
  global:
  - ERLANG_VERSION=18.3

before_install:
  - export OS_NAME=$(lsb_release -is | tr "A-Z" "a-z" || echo "osx")
  - export RELEASE=$(lsb_release -rs 2>/dev/null || sw_vers -productVersion | sed 's/^\([0-9][0-9]*.[0-9][0-9]*\).*/\1/')
  - export TARGET_DIR=${TRAVIS_BUILD_DIR}/${OS_NAME}/${RELEASE}/$(uname -m)
  - mkdir -p ${TARGET_DIR}

install:
  - curl -o `which kerl` https://raw.githubusercontent.com/yrashk/kerl/master/kerl

script: ./bin/compile

after_success: ./bin/archive

addons:
  artifacts:
    paths:
    - '${OS_NAME}'
    target_paths:
    - '/binaries/${OS_NAME}/${LSB_RELEASE}/${ARCH}'
